name: Deploy to EC2

on:
  #schedule:
    #- cron: "*/2 * * * *"
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          if [ $(node -v | cut -d '.' -f 1 | cut -d 'v' -f 2) -gt 18 ]; then
            echo \"Node version is greater than 18\"
          else
            echo \"Node version is less than or equal to 18\"
            sudo apt -y install curl
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt -y install nodejs
          fi
      - name: Check npm version
        run: npm -v
      - name: install babel
        run: sudo npm install -g babel-cli
      - name: Start the application
        run: npm start
